### ISSUE TITLE
编译直接报错！

### ISSUE THREAD

**Issue by outemancut** [KFERMercer/openwrt-v2ray#1]
/usr/lib/go-1.10/src/google.golang.org/grpc/status (from $GOROOT)
	/root/lede/build_dir/target-mipsel_24kc_musl/v2ray-core-4.21.3/.go_work/build/src/google.golang.org/grpc/status (from $GOPATH)

Cleaning module download cache (golang/go#27455)
flag provided but not defined: -modcache
usage: clean [-i] [-r] [-n] [-x] [-cache] [-testcache] [build flags] [packages]
Run 'go help clean' for details.

Makefile:305: recipe for target '/root/lede/build_dir/target-mipsel_24kc_musl/v2ray-core-4.21.3/.built' failed
make[3]: *** [/root/lede/build_dir/target-mipsel_24kc_musl/v2ray-core-4.21.3/.built] Error 1
make[3]: Leaving directory '/root/lede/package/lean/v2ray'
time: package/lean/v2ray/compile#2.53#1.67#19.64
package/Makefile:111: recipe for target 'package/lean/v2ray/compile' failed
make[2]: *** [package/lean/v2ray/compile] Error 2
make[2]: Leaving directory '/root/lede'
package/Makefile:107: recipe for target '/root/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/root/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/root/lede'
/root/lede/include/toplevel.mk:216: recipe for target 'world' failed

**Comment by KFERMercer** [comment]
梯子开全局
