### ISSUE TITLE
导致SSR Plus+无法启动

### ISSUE THREAD

**Issue by garypang13** [KFERMercer/openwrt-v2ray#2]
日志中只提示一行
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) OpenWrt - Release 1 Started!
软件包中显示V2ray 4.21.3安装成功,
但是SSR Plus+始终无法启动.

**Comment by KFERMercer** [comment]
你用的不是我的项目.
如果是我的项目, 在日志里的输出会是
`V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) OpenWrt - KFERMercer - Release 1 Started!`

**Comment by garypang13** [comment]
> 你用的不是我的项目.
> 如果是我的项目, 在日志里的输出会是
> `V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) OpenWrt - KFERMercer - Release 1 Started!`

不好意思,是我粗心复制错日志信息了,日志里输出的确实是
> `V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) OpenWrt - KFERMercer - Release 1 Started!`
![2019-11-29 10-37-3](https://user-images.githubusercontent.com/48883331/69839925-87bd2080-1294-11ea-9828-bf9207601f41.png)
用lean 固件里自带的v2ray,启动正常,当我更新到您项目的v2ray后SSR Plus就无法启动了.

**Comment by KFERMercer** [comment]
有时间我会测试下

**Comment by garypang13** [comment]
> 有时间我会测试下

我在lean lede的issue里找到个用您项目编译好的v2ray ipk,发现能正常使用,但是我自己用您项目源码编译的就一直启动不了.我自己编译的ipk大小是6.08M ,那个能正常使用的ipk文件大小是9.97M,环境是X86 64

**Comment by garypang13** [comment]
> > 有时间我会测试下
> 
> 我在lean lede的issue里找到个用您项目编译好的v2ray ipk,发现能正常使用,但是我自己用您项目源码编译的就一直启动不了.我自己编译的ipk大小是6.08M ,那个能正常使用的ipk文件大小是9.97M,环境是X86 64

我刚确认了下,那个能正常启动的v2ray ipk并不是用您项目编译的,
日志信息为
2019-11-29 11:00:57 V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom Started!
并没有 KFERMercer 或者 Lean等相关信息,应该是他自己修改而来的.

**Comment by garypang13** [comment]
> > > 有时间我会测试下
> > 
> > 
> > 我在lean lede的issue里找到个用您项目编译好的v2ray ipk,发现能正常使用,但是我自己用您项目源码编译的就一直启动不了.我自己编译的ipk大小是6.08M ,那个能正常使用的ipk文件大小是9.97M,环境是X86 64
> 
> 我刚确认了下,那个能正常启动的v2ray ipk并不是用您项目编译的,
> 日志信息为
> 2019-11-29 11:00:57 V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom Started!
> 并没有 KFERMercer 或者 Lean等相关信息,应该是他自己修改而来的.

https://github.com/coolsnowwolf/lede/issues/2065#issuecomment-553357651

**Comment by KFERMercer** [comment]
按理说应该是那个启动不起来才对。。我测试下再说吧。

**Comment by KFERMercer** [comment]
测试过后发现的确有问题, 已经修好了, 感谢提交.
